### ISSUE TITLE
Error in JSON to DataFrame

### ISSUE THREAD

**Issue by shadowdoc** [mdai/mdai-client-py#26]
I'm getting an error when trying to use common_utils.json_to_dataframe: 

This is a fresh install of the library from today.

```
Traceback (most recent call last):
  File "results.py", line 5, in <module>
    results = mdai.common_utils.json_to_dataframe(json_path)
  File "/Users/mkohli/dev/erc/lib/python3.7/site-packages/mdai/utils/common_utils.py", line 84, in json_to_dataframe
    result.columns = ["labels", "groupId", "groupName"]
  File "/Users/mkohli/dev/erc/lib/python3.7/site-packages/pandas/core/generic.py", line 5192, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 67, in pandas._libs.properties.AxisProperty.__set__
  File "/Users/mkohli/dev/erc/lib/python3.7/site-packages/pandas/core/generic.py", line 690, in _set_axis
    self._data.set_axis(axis, labels)
  File "/Users/mkohli/dev/erc/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 183, in set_axis
    "values have {new} elements".format(old=old_len, new=new_len)
ValueError: Length mismatch: Expected axis has 0 elements, new values have 3 elements
```

**Comment by anoukstein** [comment]
It looks like there something off with the labels. Can you tell me which project you the json from or forward me the json?

Then I can write code to protect against that.
Anouk
